const Prescription = require('../models/Prescription');
const PDFDocument = require('pdfkit');

const createPrescription = async (req, res) => {
  const prescription = await Prescription.create({ ...req.body, doctorId: req.user._id });
  await prescription.populate([{ path: 'patientId', select: 'name age gender' }, { path: 'doctorId', select: 'name specialization' }]);
  res.status(201).json(prescription);
};

const getPrescriptions = async (req, res) => {
  const { patientId, page = 1, limit = 20 } = req.query;
  const query = {};
  if (req.user.role === 'doctor') query.doctorId = req.user._id;
  if (patientId) query.patientId = patientId;
  const skip = (page - 1) * limit;
  const [prescriptions, total] = await Promise.all([
    Prescription.find(query).populate('patientId', 'name age gender').populate('doctorId', 'name specialization').skip(skip).limit(Number(limit)).sort('-createdAt'),
    Prescription.countDocuments(query),
  ]);
  res.json({ prescriptions, total, pages: Math.ceil(total / limit) });
};

const getPrescription = async (req, res) => {
  const prescription = await Prescription.findById(req.params.id).populate('patientId').populate('doctorId', 'name specialization phone');
  if (!prescription) return res.status(404).json({ message: 'Not found' });
  res.json(prescription);
};

const updatePrescription = async (req, res) => {
  const prescription = await Prescription.findByIdAndUpdate(req.params.id, req.body, { new: true });
  if (!prescription) return res.status(404).json({ message: 'Not found' });
  res.json(prescription);
};

const downloadPrescriptionPDF = async (req, res) => {
  const prescription = await Prescription.findById(req.params.id).populate('patientId').populate('doctorId', 'name specialization phone');
  if (!prescription) return res.status(404).json({ message: 'Not found' });

  const doc = new PDFDocument({ margin: 50 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=prescription-${prescription._id}.pdf`);
  doc.pipe(res);

  doc.fontSize(22).font('Helvetica-Bold').text('MediCare Clinic', { align: 'center' });
  doc.fontSize(10).font('Helvetica').text('AI-Powered Healthcare Management', { align: 'center' });
  doc.moveDown(0.5);
  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown(0.5);

  const p = prescription.patientId;
  const d = prescription.doctorId;
  doc.fontSize(11).font('Helvetica-Bold').text('PATIENT', { underline: true });
  doc.font('Helvetica').fontSize(10).text(`${p.name}  |  Age: ${p.age}  |  Gender: ${p.gender}`);
  doc.text(`Date: ${new Date(prescription.createdAt).toDateString()}`);
  doc.moveDown(0.5);
  doc.fontSize(11).font('Helvetica-Bold').text('PRESCRIBED BY', { underline: true });
  doc.font('Helvetica').fontSize(10).text(`Dr. ${d.name}  |  ${d.specialization || 'General Physician'}`);
  doc.moveDown(0.5);

  if (prescription.diagnosis) {
    doc.fontSize(11).font('Helvetica-Bold').text('DIAGNOSIS', { underline: true });
    doc.font('Helvetica').fontSize(10).text(prescription.diagnosis);
    doc.moveDown(0.5);
  }

  doc.fontSize(11).font('Helvetica-Bold').text('MEDICINES', { underline: true });
  doc.moveDown(0.3);
  prescription.medicines.forEach((med, i) => {
    doc.font('Helvetica-Bold').fontSize(10).text(`${i + 1}. ${med.name}`);
    doc.font('Helvetica').fontSize(10).text(`   Dosage: ${med.dosage}  |  Frequency: ${med.frequency}  |  Duration: ${med.duration}`);
    if (med.instructions) doc.text(`   Note: ${med.instructions}`);
    doc.moveDown(0.3);
  });

  if (prescription.instructions) {
    doc.fontSize(11).font('Helvetica-Bold').text('INSTRUCTIONS', { underline: true });
    doc.font('Helvetica').fontSize(10).text(prescription.instructions);
  }

  if (prescription.aiExplanation) {
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica-Bold').text('AI PATIENT EXPLANATION', { underline: true });
    doc.font('Helvetica').fontSize(10).text(prescription.aiExplanation);
  }

  if (prescription.followUpDate) {
    doc.moveDown(0.5);
    doc.font('Helvetica-Bold').fontSize(10).text(`Follow-up: ${new Date(prescription.followUpDate).toDateString()}`);
  }

  doc.moveDown(2);
  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown(0.3);
  doc.fontSize(9).font('Helvetica').fillColor('gray').text('Generated by MediCare SaaS | Powered by AI', { align: 'center' });
  doc.end();
};

module.exports = { createPrescription, getPrescriptions, getPrescription, updatePrescription, downloadPrescriptionPDF };